### ISSUE TITLE
Fix Style errors in Typescript

### ISSUE THREAD

**Issue by choyiny** [choyiny/mobile-wizard#67]

**Comment by trblackw** [comment]
I can work on this 😎

**Comment by icancode007** [comment]
I can take a shot at this

**Comment by choyiny** [comment]
Thanks!

**Comment by icancode007** [comment]
My mistake I didn't see this was Angular, sorry trusted the filter too much. Still open if anyone wants to take a shot.

**Comment by choyiny** [comment]
If you are still up for this, simply run the `.ts` files with a linter. Typescript is basically javascript with type annotations.

**Comment by tabuckner** [comment]
@choyiny I've got it.

**Comment by tabuckner** [comment]
https://github.com/choyiny/mobile-wizard/pull/73/files
