### ISSUE TITLE
Fix style errors (PEP8) in Python

### ISSUE THREAD

**Issue by choyiny** [choyiny/mobile-wizard#68]

**Comment by tiao** [comment]
working on this.

**Comment by Daniel-I-Am** [comment]
Sorry, hadn't noticed the comment so opened the PR already, ah well. A choice can be made between the two options :)

**Comment by tiao** [comment]
No problem. I'm can to try improve your PR. Add Makefile to run lint tool and try fix others warnings.

**Comment by choyiny** [comment]
@tiao If you can open a PR to automatically check for PEP8 errors using github actions, feel free to work on it!
